version: '3'
services:
  back:
    build:
      context: .
      dockerfile: ./letalkTest-back/Dockerfile
    container_name: "letalkBack"
    volumes:
      - ./letalkTest-back:/app
    working_dir: /app
    ports: 
      - 3000:3000

  front:
    build:
      context: .
      dockerfile: ./letalkTest-front/Dockerfile
    container_name: "letalkFront"
    environment:
      - VITE_BASE_URL=http://localhost:3000
    volumes:
      - ./letalkTest-front:/app
    working_dir: /app
    ports: 
      - 3001:3001
